### ISSUE TITLE
ModuleNotFoundError: No module named 'robohusky.train.tcsloader'

### ISSUE THREAD

**Issue by BillSiriusLiu** [EmbodiedGPT/EmbodiedGPT_Pytorch#8]
Great work for embodied intelligence!
I run into this error when I run the train bash file. It seems like a file tcsloader is missing in directory robohusky/train/ . Or maybe there are some packages I need to install before training?
BTW, what is this whole robohusky model? Is it part of EmbodiedGPT work or is it a framework from other project? 

More detailed error message is listed below.
``` bash
Traceback (most recent call last):
  File "./train.py", line 54, in <module>
    from robohusky.base_dataset import (
  File "/root/EmbodiedGPT_Pytorch/robohusky/base_dataset.py", line 12, in <module>
    from robohusky.train.tcsloader import TCSLoader
ModuleNotFoundError: No module named 'robohusky.train.tcsloader'
```
I put the train.py and inference.py script into the root directory of this project to solve the path problem. That is, these scripts do not import robohusky from it's parallel directory. And that's why I wonder if I need to install this robohusky package or do something to solve this issue?

**Comment by Gavin218** [comment]
I meet the same problem. Can someone solve it?
